INSERT INTO CATEGORY (DESCRIPTION) VALUES ('American');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('Italian');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('Mexican');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('Fast Food');

